# Generated by Django 5.1.1 on 2024-09-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=255)),
                ('scraped_at', models.DateTimeField()),
                ('status', models.BooleanField(default=True)),
                ('domain', models.CharField(max_length=255)),
            ],
        ),
    ]
