name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      working-directory: web
      run: |
        python -m pip install --upgrade pip
        pip install -r web/requirements.txt

    - name: Run migrations
      working-directory: web
      run: |
        python manage.py migrate

    - name: Run tests
      working-directory: web
      run: |
        python manage.py test
